### ISSUE TITLE
Add draw type option?

### ISSUE THREAD

**Issue by CrabBucket** [Nilirad/bevy_prototype_lyon#10]
Currently Bevy considers a (0.0,0.0) x,y cursor location to be on the bottom left of the screen.   Your position would consider this to be the center of the screen. 

The solution would seem to then be set some kind of draw type option that allowed you to do your coordinates based on center bottom left top right or whatever is convenient.

**Comment by Nilirad** [comment]
The way shapes are drawn on screen depend on camera's transform. When you create a shape or a path, you specify the positions in world coordinates.

**Comment by CrabBucket** [comment]
Yes but at some you interpret the Transform correct?  For example when you draw a circle to a 0 Transform it draws in the top right in the center of the camera (center screen in at all times in my case since the camera is static).  Now lets say given the exact same 0 Transform you could draw a circle to the top right (or any other offset). 

The solution on my end is simple when creating  a primitive shape offset the Transform coordinates by the size of your screen to get it into the correct location.  I guess I'm not entirely sure at the end of the day who should be the one who to do this offset, all I know is that it should not be an end user of bevy or your library.  Maybe the solution is just to create a new library that just does this screen offset? All I know is in similar tools like yours when I create primitives say like Rect or Ellipse I specify a drawmode like center or corner something along those lines for where it should offset the whole shape based on your type for example If draw mode for a rect is Center it will create the rect such that the center of the rectangle lies on your transform however it the rect was like BottomCorner it would draw the bottom left corner to the coordinate.  This is different from my proposal but not drastically so.  I guess I could just create a wrapper around your primitive() function that just adds this parameter for my own use. 

Sorry for rambling a bit but this is an issue I find I often run into when drawing to screen and my solution every time is having to reason about the offset myself which just introduces yet another important compute that can give strange effects but not error when wrong.

**Comment by faassen** [comment]
I'm trying to use this with bevy_rapier2d. I've implemented a system that sets up sprite bundles based on bevy_prototype_lyon. bevy_rapier2d then keeps this in sync with the physics engine, meaning that objects are located, rotated and stretched according to the information in the physics simulation. I think the Circle primitive renders in the center, so positioning and rotation is all right. But for Rect the draw point is, I think, the top right corner and the physics engine assumes the center. This means that the rectangle is drawn to the right of the center.

I could (I think) put in an adjust to the translation to reposition the drawing, but the way bevy_rapier works is that it keeps overriding the transform based on the physics engine and it assumes center rendering. So there isn't really a good place to adjust the positioning. If I could tell primitives where they should have their center, and it retains this center independently of the transform, I think it would work.

Note: I don't know much about any of this yet so there may be a simple solution I just don't see.

**Comment by Nilirad** [comment]
@faassen I think the best you can do for now is creating a custom mesh using the [path](https://docs.rs/bevy_prototype_lyon/0.1.5/bevy_prototype_lyon/path/index.html) module. With paths, you have complete control over the shape you are creating.
