### ISSUE TITLE
Recoloring a shape or tinting

### ISSUE THREAD

**Issue by payload** [Nilirad/bevy_prototype_lyon#104]
I like using geometric shapes for prototyping game mechanics.
I have the use case where I want to draw a lot of shapes having the same path but different colors.
Those entities are created and removed on mass.
Think of like items on a belt like https://shapez.io

👉 Creating one shape bundle / mesh and tinting it would be what I would have expected, but it did not look like this is possible right now by changing the ShapeColors, since colors are backed into vertex attributes and shaders only look at vertex attributes.

I currently rely on creating lots of shape bundles with freshly build meshes but on color change I mutate the color vertex attributes like in following code snippet. To distinguish stroke vertices from filling vertices I use a black stroke only and check for this color. 🤪

```rust
               for mesh in meshes.get_mut(&*mesh) {
                    if let Some(VertexAttributeValues::Float4(colors)) = mesh.attribute_mut(Mesh::ATTRIBUTE_COLOR) {
                        for color in colors {
                            if color[..3] != [0.0, 0.0, 0.0] {
                                *color = item.color().as_rgba_f32();
                            }
                        }
                    }
                }
```

I think what I am doing is fragile but I lack an API to support this use case. How would this look like?

**Comment by Nilirad** [comment]
You can actually create multiple shapes using the same path but using different colors.

Take a look for example at the function signature of `GeometryBuilder::build_as`:

```rust
pub fn build_as(
        shape: &impl Geometry, // insert the same Path over and over
        colors: ShapeColors, // use a different color every single time
        mode: DrawMode,
        transform: Transform,
    ) -> ShapeBundle
```

**Comment by payload** [comment]
I'll try that. 👍
