### ISSUE TITLE
[IMPORTANT] Relicense bevy_prototype_lyon under dual MIT/Apache 2.0

### ISSUE THREAD

**Issue by Nilirad** [Nilirad/bevy_prototype_lyon#105]
I, as the repository owner, would like to make a few simple but important changes to `bevy_prototype_lyon`:

1. relicense it under the "dual MIT / Apache 2.0 license",
2. remove the copyright notice that now resides in the LICENSE file, which incorrectly attributes the work to only me.

Each contributor holds copyright for their additions. Therefore, I **cannot relicense without explicit consent from past contributors**, unless I remove their contributions. The purpose of this issue is seeking compliance for these changes from all the contributors.

## Why I am going to relicense

The Bevy game engine, which this library depends on, is currently under the same process (bevyengine/bevy#2373) and its current contribution guidelines suggests to license eligible assets under the same license as Bevy. Also, there is a remote possibility that at least some parts of `bevy_prototype_lyon` will be included in a future version of Bevy. Relicensing would be of great help in this case.

## How to comply

If you decided to comply to the changes described in the first paragraph of this issue, I really appreciate it. Thanks! You just need to post the following comment as a reply to this issue:

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```

By posting this comment, everyone can safely assume that you agree with the relicense process. Please notice that other forms of support, like reacting with a 👍🏻 or posting a comment with a different formula *will NOT be considered valid*.

### What if you don't want to comply

I don't want to force you to comply to these changes. You will need to know however that if you don't comply, your contributions will be removed (or reimplemented in a way that respects your copyright) in order to keep the relicense process going on. Please let me know under this issue or privately if you take this choice. It would help me a lot speeding up the process. Still, thanks for having contributed to this repository!

### README.md

the following paragraphs will be added to the end of the file:

```
### License

Licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any
additional terms or conditions.
```

### License files

LICENSE will be replaced by LICENSE-MIT and LICENSE-APACHE with their respective contents.

### Rust package manifest (Cargo.toml)

the `license` field will be changed to the following:

```
license = "MIT OR Apache-2.0"
```

## Contributor checklist

The following is a checklist featuring every GitHub account that have committed at least once in this repository, aside from myself (order is alphabetical):

- [x] @alec-deason 
- [x] @alyti 
- [x] @carrascomj 
- [x] @davidB 
- [x] @faassen 
- [x] @nside 
- [x] @pka 
- [x] @ssbr 
- [x] @TheLeonsver1
- [x] @will-hart 

*This issue will be closed once a pull request with the needed changes will be merged to the `master` branch.*

**Comment by nside** [comment]
I license past and future contributions to this repository under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by alyti** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by carrascomj** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by TheLeonsver1** [comment]
I license past and future contributions to this repository under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by faassen** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to choose either at their option.

**Comment by davidB** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by will-hart** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by ssbr** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

(Sorry for delay, had to check with employer as they own the copyright.)

**Comment by alec-deason** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by pka** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Nilirad** [comment]
Thank you all for your fast responses. I'll proceed as soon as possible.

I am going to edit the closing conditions for this issue. The issue will be closed when the PR will be merged.
