### ISSUE TITLE
Modifying shapes after creation

### ISSUE THREAD

**Issue by Bauxitedev** [Nilirad/bevy_prototype_lyon#11]
Not sure if I'm doing it incorrectly, but right now it seems difficult if not impossible to modify the shapes at runtime after they've been created.

E.g. if I have a simple path shape like this...

```rust
    let points = vec![point(0.0, 0.0), point(100.0, 100.0), point(500.0, 000.0)];

    let shape = ShapeType::Polyline {
        points,
        closed: false,
    };
    let mut stroke_options = StrokeOptions::default();
    stroke_options.line_width = 1.0;

    cmd.spawn(primitive(
        material,
        &mut meshes,
        shape,
        TessellationMode::Stroke(&stroke_options),
        Vec3::zero(),
    ))
```

It seems if I want to change the shape afterwards, I need to use its `Mesh` component...

```rust
fn update(mut meshes: ResMut<Assets<Mesh>>, h: &Handle<Mesh>) {
    let mesh = meshes.get_mut(h).unwrap();
    let attributes = &mut mesh.attributes;

    for att in &mut attributes.iter_mut() {
        //TODO do something with attr
    }
}
```

But it seems the points it returns are the ones *after* tessellating the shape, which is not very useful if you want to move the original points *before* tessellation. E.g. it seems to return 6 points instead of the expected 3.

I assume the only way to do this right now is to create a new primitive every frame and delete the old one?

**Comment by CrabBucket** [comment]
Yeah, What I have been doing is creating a new primitive SpriteBundle every time I want to change shape then just setting the specific entities mesh (and shape but not sure its needed) to the newly created ones.   so like if the handle was mutable `h= primitive(... options).mesh
