### ISSUE TITLE
Stuttering on some hardware

### ISSUE THREAD

**Issue by CleanCut** [Nilirad/bevy_prototype_lyon#140]
Just as an FYI, I'm experiencing stutter in Bevy 0.6 when I add plugins for projects like this one. Literally just adding the plugin introduces stutter -- I don't even need to _do_ anything.

I reported it upstream to Bevy [here](https://github.com/bevyengine/bevy/issues/3709).  I just wanted to make you aware in case other users of this plugin experience it, or if you are interested in looking into the problem.

Feel free to close this issue unless you feel like it provides some value while the problem persists.

**Comment by Nilirad** [comment]
Thanks for the heads up. I'll keep it open for future reference.

**Comment by CleanCut** [comment]
Resolved in upstream bevy.
