### ISSUE TITLE
Compatibility with bevy ui

### ISSUE THREAD

**Issue by Inky-developer** [Nilirad/bevy_prototype_lyon#15]
If I am not mistaken, it is currently not possible to combine this crates functionality with bevy ui components.
It seems like `NodeComponents` always renders in front of a primitive. It is also not possible to add a primitive as a child to a `NodeComponent`.

**Comment by Nilirad** [comment]
Yes, you're right. I'm using the `SpriteComponents` bundle to create the shapes. The UI, if I'm correct, is rendered using the UiCamera, while the sprites with the 2D camera. I think the best way to achieve that is waiting for bevyengine/bevy#90

**Comment by dcz-self** [comment]
I managed to get this in the UI: https://github.com/dcz-self/breedmatic/blob/54c75ec0fed0eb958aec7c9459e9ad25f3f9eebb/src/viewer.rs#L116

XY positioning works, but z-order gave me trouble. I don't know how that works, but it seems all I could do is change the order of drawing.

**Comment by Nilirad** [comment]
Fixed by #114.
