### ISSUE TITLE
Heron 2d debug2d feature conflict

### ISSUE THREAD

**Issue by jakyle** [Nilirad/bevy_prototype_lyon#166]
very simillar to the bevy_conosole issue #126 , when using Heron 2dDebug feature flag, there is a conflict with a shapes stage

```
thread 'main' panicked at 'Stage already exists: Shape.',
```

this conflict occurs with Heron 3.0

**Comment by Nilirad** [comment]
This has been solved on the master branch by #163. I'll release a new version when Bevy 0.8 comes out.
