### ISSUE TITLE
rust-toolchain file

### ISSUE THREAD

**Issue by Vrixyz** [Nilirad/bevy_prototype_lyon#18]
While working on https://github.com/Nilirad/bevy_prototype_lyon/pull/17 : It seemed that rust compiler needs to be nightly ?

A word about that on the readme and/or a `rustup-toolchain` file would make it clear and self documented.

**Comment by Nilirad** [comment]
Yeah, it was because the .cargo/config file for fast builds was versioned. I changed that recently to match the Bevy style.

Now it's possible to use any toolchain to build this crate.
