### ISSUE TITLE
Does this crate allow for transparency?

### ISSUE THREAD

**Issue by ShadowMitia** [Nilirad/bevy_prototype_lyon#19]
Hello there!

I've been playing around with this crate, and I wanted to have some coloured circles overlap with some transparency.
I saw that I had to activate the transparency on the `SpriteComponents`'s draw attribute but it still doesn't seem to work?

I'm probably doing something wrong, but I can't seem to be finding what.

Here's a minimal example using bevy 3.0 and bevy_lyon 0.1.3 (and running on Linux if that helps) :

```rust
use bevy::prelude::*;
use bevy_prototype_lyon::prelude::*;

fn build_transparent_circles(
    mut commands: Commands,
    mut materials: ResMut<Assets<ColorMaterial>>,
    mut meshes: ResMut<Assets<Mesh>>,
) {
    for (i, color) in vec![Color::GREEN, Color::RED, Color::BLUE]
        .iter()
        .enumerate()
    {
        let material = materials.add(ColorMaterial::color(*color));
        let mut sprite = primitive(
            material,
            &mut meshes,
            ShapeType::Circle(100.0),
            TessellationMode::Fill(&FillOptions::default()),
            Vec3::new(i as f32 * 60.0, 0.0, 0.0),
        );
        sprite.draw = Draw {
            is_transparent: false,
            ..Default::default()
        };

        commands.spawn(sprite);
    }
}

fn setup_system(
    mut commands: Commands,
    materials: ResMut<Assets<ColorMaterial>>,
    meshes: ResMut<Assets<Mesh>>,
) {
    commands
        .spawn(UiCameraComponents::default())
        .spawn(Camera2dComponents::default());

    build_transparent_circles(commands, materials, meshes);
}

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(setup_system.system())
        .run();
}
```

**Comment by Nilirad** [comment]
Hello! Sorry for being late 😅
Bevy supports rgba colors, so you can directly use the alpha channel to set the transparency. I added an [example](https://github.com/Nilirad/bevy_prototype_lyon/blob/master/examples/transparency.rs) to show that.

**Comment by ShadowMitia** [comment]
No worries! Thanks for the response!
I guess I never realised that you need to pass rgba and not rgb... Can't remember what I was trying to do, but your example is helpful, thank you!
