### ISSUE TITLE
Support for rounded polygons

### ISSUE THREAD

**Issue by wainwrightmark** [Nilirad/bevy_prototype_lyon#194]
[A recent pull request](https://github.com/nical/lyon/pull/849) (by me) to `lyon` added support for rounded polygons. It would be nice to add a `RoundedPolygon` struct here to use let people use them. The API would be the same as for `Polygon` but with an addition `radius` field.  

I'm happy to submit a PR doing this. The only issue is that this would add a dependency on the `main` branch of `lyon_algorithms` .  The alternative (apart from waiting) would be to duplicate the code (about 100 lines) here and then remove it again on the next minor release of `lyon_algorithms`.

**Comment by laundmo** [comment]
I for one would really appreciate a PR even if it includes a main branch (commit id is probably better) or duplicated code, as i'd love to depend directly on it.

**Comment by wainwrightmark** [comment]
> I for one would really appreciate a PR even if it includes a main branch (commit id is probably better) or duplicated code, as i'd love to depend directly on it.

This is my branch at the moment. It's now a couple of commits behind though. 
https://github.com/wainwrightmark/bevy_prototype_lyon
Let me know if it works for you.  
When I have time I'll do a proper PR

**Comment by rparrett** [comment]
lyon_algorithms 1.0.3 was recently published which includes your new code.

I'd personally love to see the feature integrated.

**Comment by Nilirad** [comment]
I see no problem in adding `lyon_algorithms` as a dependency, so I'm ok with this feature 😀
