### ISSUE TITLE
Could arcs be added to shapes?

### ISSUE THREAD

**Issue by Olexorus** [Nilirad/bevy_prototype_lyon#2]
Hi, I just saw you published this, thanks for creating it, having a way of drawing shapes in Bevy without needing sprites is exactly what I was waiting for.

I was wondering if drawing arcs (i.e. shapes like half of a circle, or a different fraction of a circle) is possible yet, and in case not, if you have plans to add this in the future?

**Comment by Nilirad** [comment]
Arcs are possible using lyon, but I didn't implement them here since I didn't want to delay too much the release. I'll add them soon. In the meantime, since PathBuilder struct has the lyon builder as its public field, you can use it to add an arc to the path.

**Comment by Olexorus** [comment]
Ok awesome, thanks again!

**Comment by Nilirad** [comment]
Feature merged. Closing issue.
