### ISSUE TITLE
Docs.rs still shows 0.7.2 as latest version

### ISSUE THREAD

**Issue by akappel** [Nilirad/bevy_prototype_lyon#206]
It looks like the library has been updated with some new design patterns in 0.8, but Docs.rs seems to still only show 0.7.2 as the latest. Is this something that it will pickup eventual, or does this need manual intervention?

**Comment by Nilirad** [comment]
It should sort itself out. docs.rs has a queue, and usually it takes some hours. I think it's taking longer because of the growing popularity of Rust, but the hardware setup for the service wasn't upgraded.

**Comment by akappel** [comment]
Awesome, no worries! For now I ran `cargo doc -p bevy_prototype_lyon --open` to view the latest docs locally. Thanks @Nilirad
