### ISSUE TITLE
Expected bevy_render::color::Color, found bevy::prelude::Color

### ISSUE THREAD

**Issue by quantumpotato** [Nilirad/bevy_prototype_lyon#214]
Error shows when trying to follow the readme and do a `Stroke::new(Color::BLUE, 10.0)`

"the trait bevy::prelude::Bundle is not implemented for bevy_prototype_Lyon:entity:ShapeBundle, bevy_prototype_lyon::draw::Fill, bevy_prototype:lyon::draw:Stroke"

I cloned the bevy project and am running this in the Breakout example with the import added:

`"use bevy_prototype_lyon::prelude::*;` and adding `.add_plugin(ShapePlugin)`

**Comment by Nilirad** [comment]
Sorry for the delay, but from the error type it looks like there's a mismatch between the Bevy version your crate is depending on and the Bevy version `bevy_prototype_lyon` is depending on.

**Comment by quantumpotato** [comment]
Yes, I had the issue because I was running from within the bevy example project. Thanks!
