### ISSUE TITLE
Cannot compile when using bevy_webgl2

### ISSUE THREAD

**Issue by Circuit8** [Nilirad/bevy_prototype_lyon#23]
Hi there,

I'm having trouble getting my project to compile with https://github.com/mrk-its/bevy_webgl2.

Anyone else have any idea about how to workaround this?

Thanks in advance. And thanks for this library, I've been getting some great use out of it!

**Comment by Nilirad** [comment]
There's a known problem with `lyon v0.16`, where it fails to compile with 250+ errors. I'm currently upgrading to depend on 1.17 to fix. Try to see if your problem is similar to nical/lyon#619

**Comment by Circuit8** [comment]
@Nilirad yes looks really similar to that. I'll keep an eye out for the upgrade, cheers.

**Comment by Nilirad** [comment]
I just published the new version. It should work now. There are a few API changes

**Comment by Circuit8** [comment]
Awesome, much appreciated 😄
