### ISSUE TITLE
Bevy tracking link in README badge is broken

### ISSUE THREAD

**Issue by manankarnik** [Nilirad/bevy_prototype_lyon#230]
## Description
 Bevy has moved its plugin guidelines to the Bevy Book on the website. As a result, the bevy tracking link is broken. Willing to create a PR for the same if required.
See https://github.com/bevyengine/bevy/issues/11272
## Possible Fixes
- Update the tracking link in badge to https://bevyengine.org/learn/book/plugin-development/#main-branch-tracking
- Provide a section in README explaining the badge and link to it
- Remove the badge from README
- Do nothing

**Comment by Nilirad** [comment]
Thanks for the heads up! Feel free to open a PR with the correct link.
