### ISSUE TITLE
Draw shape helper function

### ISSUE THREAD

**Issue by Nilirad** [Nilirad/bevy_prototype_lyon#42]
Currently, to draw a shape you call the draw method of a type that implements `ShapeSprite`:
```rust
let circle = shapes::Circle {
    radius: 100.0,
    ..Default::default()
};

commands.spawn(Camera2dBundle::default()).spawn(circle.draw(
    materials.add(ColorMaterial::color(Color::AQUAMARINE)),
    TessellationMode::Fill(FillOptions::default()),
    Transform::default(),
));
```

But it may be better to use a helper function instead, that takes the `ShapeSprite` as input:
```rust
commands.spawn(Camera2dBundle::default()).spawn(draw_shape(
    Box::new(shapes::Circle {
        radius: 100.0,
        ..Default::default()
    }),
    materials.add(ColorMaterial::color(Color::AQUAMARINE)),
    TessellationMode::Fill(FillOptions::default()),
    Transform::default(),
));
```

The problem is, I can't find a way to satisfy trait bounds when I add a `Box<dyn ShapeSprite>` type as argument to the function.

**Comment by Dummyc0m** [comment]
There's probably a usability advantage to provide some basic builtin shapes like lines or quads. I don't think this draw_shape helper functions really matters that much.

**Comment by Nilirad** [comment]
Yes, I think you're right. When I wrote the example above I realized that it looks more cluttered with the box and things.
