### ISSUE TITLE
Rethink the way sprites are added to the World

### ISSUE THREAD

**Issue by Nilirad** [Nilirad/bevy_prototype_lyon#44]
The current implementation relies on two systems:

1. **The client system:** The user uses the method `ShapeSprite::draw` to spawn a `(ShapeDescriptor, )` bundle.
2. **The `shapesprite_maker` system:** Queries the `ShapeDescriptor`s, generates the corresponding sprites, and despawns the descriptors.

## The problem
While this approach removes a lot of boilerplate, the indirect creation of a sprite creates problems to users who call `Commands::{with, with_bundle, current_entity}`, since those functions point to the `ShapeDescriptor` entity that gets deleted.

### Custom command
That's the most interesting solution, because it completely removes the necessity of relying on an external system to spawn entities without boilerplate. If that is possible, the current implementation should be considered an anti-pattern. The thing is, I never made a custom command, so I don't know if it's possible.
EDIT: The way the `Command` trait and the `Commands` struct are currently designed makes it impossible to draw a shape without boilerplate.

### Direct API
In addition to the `ShapeDescriptor` based API, it's possible to add an API similar to the old one to directly draw shapes. So each user chooses what to do. This however puts the user in front of a design choice.

**Comment by alec-deason** [comment]
Why not remove the ShapeDescriptor component and attach the SpriteBundle to the same entity, rather than despawning it. I think that gives you a usable API and is the behavior I expected when I started using the tool.

**Comment by alec-deason** [comment]
I made a PR that changes to this way of doing things: #47 The examples work with this change and so does my small project.

**Comment by Nilirad** [comment]
Thanks for it. #47 merged. Closing.
