### ISSUE TITLE
Update to latest branch

### ISSUE THREAD

**Issue by carrascomj** [Nilirad/bevy_prototype_lyon#8]
Hello! This crate is awesome. I'm using it for implementing a tool for myself https://github.com/carrascomj/bevy_svg_map/tree/bevy-lyon. 

As of now, in order to be compatible with bevy's master, I had to change two lines to make it work. Are you interseted in having the master branch up to date with bevy's `HEAD`? If so, I can just submit the PR. Some may prefer to just wait for the next version of bevy anyways.

**Comment by Nilirad** [comment]
Hello, thanks for using this crate. Yes, it is a good idea for the master branch of this crate to follow the development of the master branch of Bevy. You could also change the `cargo.toml` dependency to point to the Bevy repository instead.
Then, when a new Bevy version gets released, I can make a branch, tweak the necessary things and publish on crates.io. Seems good enough.

**Comment by carrascomj** [comment]
Cool! I have submitted the PR pointing to bevy's master. I think that strategy seems very sensible for bevy plugins, I will try to make the same for mine.

**Comment by Nilirad** [comment]
Nice to hear that 😊
Merged.
