### ISSUE TITLE
WASM builds no longer work?

### ISSUE THREAD

**Issue by rparrett** [Nilirad/bevy_prototype_lyon#93]
Thanks for the library.

I started a fresh project with bevy 0.5, bevy_webgl 0.5 and (forked bevy_prototype_lyon, see my PR) based on bevy_webgl2_app_template.

Things are working great in native builds, but panicking in chrome and firefox when compiling shaders in web builds:

```
wasm.js:369 panicked at 'called `Result::unwrap()` on an `Err` value: "ERROR: 0:1: \'\n\' : invalid version directive\nERROR: 0:5: \'layout\' : syntax error\n\u{0}"', /Users/robparrett/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_webgl2-0.5.0/src/renderer/webgl2_render_resource_context.rs:77:81
```

I guess this is due to the new rendering pipeline that (became necessary for bevy 0.5 for some reason)?

I'd be happy to contribute something like a "web" feature that swaps in some opengl es compatible shaders, if that contribution would be welcome.

**Comment by alyti** [comment]
I can also reproduce this panic in my project bevy_antsim, a github pages hosted WASM build is available [here](https://alyti.github.io/bevy_antsim/).
